services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  bot:
    build: ./bot
    privileged: true
    environment:
      - ROOM_CODE=default-room
